### PR TITLE
Simplifies sum_cell_cell_energies

### PR DESCRIPTION
**Pull request by glyg**
I only made significant changes in `energy.py`, where I just factorized the distance filtering calls, e.g. 

``` python
cc_dist1 = cell_cell_distances[(cell_cell_distances < aa)]
```

instead of

``` python
cond1 = (cell_cell_distances < aa)
energy_function(cell_cell_distances[cond1])
```

The notebook runs fine.

Modifications to `events.py` are just [PEP8](http://pep8.org/) compliance modifications.
About `events.py`:
- Unless you have a really good reason for it, it might not be a good idea to define a function inside another. It is better to pass arguments (defining a function has a cost, and there might be optimisations between calls)
-  You make repeated calls to `sum_cell_cell_energies()`. It might be better to concatenate all the distances and call it only once.

### CODE REVIEW

**Comment by glyg** [comment]
As for the use of cython, I'm not sure you'd gain a lot of time if the bottleneck is the call to `cdist`, as this is already a simple call to a C function.

Another way of computing distances is through the use of [`KDTrees`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.html#scipy.spatial.cKDTree). The logic is a bit different, but it might be more efficient here: for the mother and both daughter cells, it would mean finding the pairs with dist < aa, bb and cc, computing distance on those and applying the energy terms separately.

Also worth mentioning is `numexpr`, which might boost computation times on simple algebraic calls.

**Comment by petermchale** [comment]
@glyg 

Thanks for your pull request, which I just merged.

Regarding defining functions within functions, I agree that moving `update_tumor_energy` out of `execute_relaxation_event` would speed things up. But my profiling showed that most of the time spent in `update_tumor_energy` was due to time spent in `cdist` and `sum_cell_cell_energies`. Doesn't this imply that whatever inefficiency is associated with defining functions within functions is not rate-limiting? 

Regarding computing inter-cell distances. I agree with your remark about Cython and cdist. I didn't understand your remark about `KDTrees`, but it seems to hinge upon mother-daughter relationships. However the bottleneck is not in dividing cells but in moving them about so as to relax the tissue. If your idea holds also in this case , then please try to convey the idea once again. 

I will implement `numexpr` in `sum_cell_cell_energies`, which could have a significant impact. Thanks. 

Please let me know if you end up implementing the `tumor` model in `tyssue`.

**Comment by glyg** [comment]
Hi Peter
Thanks for the merge.

> But my profiling showed that most of the time spent in update_tumor_energy was due to time spent in cdist and sum_cell_cell_energies. Doesn't this imply that whatever inefficiency is associated with defining functions within functions is not rate-limiting? 

You're right on a performance point of view, but the number of cells is relatively small (about 100?), and I think the changes I did might facilitate things when the size of the system increases (because of initiation time overheads).

For the same reason, it is better to factor all the calls to the rate limiting functions (cdist and sum_cell_cell_energies).

> I didn't understand your remark about KDTrees, but it seems to hinge upon mother-daughter relationships. 

I wasn't clear for KDTrees,  I was thinking you could use it instead of the cdist calls.But I'm not sure it would be usefull (from [scipy's doc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.html#scipy.spatial.cKDTree)) : 

> For large dimensions (20 is already large) do not expect this to run significantly faster than brute force. High-dimensional nearest-neighbor queries are a substantial open problem in computer science.

I'll surely try to implement this in tyssue at some point in the near future, I'll keep you posted

**Comment by petermchale** [comment]
Guillaume, 

I re-wrote `sum_cell_cell_energies` using `numexpr` and put in the 'optimization' branch of the `tumor` repo. The change actually slows down the simulation for the parameter values I tested. Let me know if you find different. 

Thanks, 
Peter

**Pull request merged**
